# Generated by Django 4.2.6 on 2023-10-20 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chat',
            old_name='created_at',
            new_name='timeOfMessage',
        ),
    ]
