# Generated by Django 4.2.6 on 2023-10-20 07:11

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chatbot', '0002_rename_created_at_chat_timeofmessage'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Chat',
            new_name='ChatSchema',
        ),
    ]
